# Site settings
author: George Hardcastle
title: 
header-img: img/home-bg.png
email: th3g0r327.gh@gmail.com
copyright_name: George Hardcastle
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: th3badw0lf27
github_username:  gcastle27

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
